# Generated by Django 4.2.7 on 2023-12-26 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestRoutine10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('which_test', models.CharField(choices=[('40問', '40問'), ('10問', '10問')], max_length=100, verbose_name='テストの種類')),
                ('category', models.TextField()),
                ('test_result', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('which_test', models.CharField(choices=[('40問', '40問'), ('10問', '10問')], max_length=100, verbose_name='テストの種類')),
                ('test_result', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='問題')),
                ('answer', models.TextField(verbose_name='正解')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='解説')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像')),
                ('hint', models.TextField(blank=True, null=True, verbose_name='ヒント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shoseki_page', models.CharField(blank=True, max_length=255, null=True, verbose_name='書籍ページ')),
                ('shoseki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqlapp.book', verbose_name='書籍')),
            ],
        ),
    ]
