# Generated by Django 4.2.7 on 2024-01-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0002_category_alter_practice_shoseki_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicechoice',
            name='thumbnailA1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像1 (正解用)'),
        ),
        migrations.AlterField(
            model_name='practicechoice',
            name='thumbnailA2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像2 (正解用)'),
        ),
        migrations.AlterField(
            model_name='practicechoice',
            name='thumbnailA3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像3 (正解用)'),
        ),
        migrations.AlterField(
            model_name='practicechoice',
            name='thumbnailQ1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像1 (問題用)'),
        ),
        migrations.AlterField(
            model_name='practicechoice',
            name='thumbnailQ2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像2 (問題用)'),
        ),
        migrations.AlterField(
            model_name='practicechoice',
            name='thumbnailQ3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像3 (問題用)'),
        ),
    ]
