# Generated by Django 4.2.7 on 2024-01-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0005_codepractice_thumbnailq10_codepractice_thumbnailq6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepractice',
            name='question2',
            field=models.TextField(blank=True, null=True, verbose_name='問題'),
        ),
        migrations.AlterField(
            model_name='codepractice',
            name='question3',
            field=models.TextField(blank=True, null=True, verbose_name='問題'),
        ),
    ]
