# Generated by Django 4.2.7 on 2024-01-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0007_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ11',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像11 (問題用)'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ12',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像12 (問題用)'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ13',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像13 (問題用)'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ14',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像14 (問題用)'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ15',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像15 (問題用)'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ16',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像16 (問題用)'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ17',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像17 (問題用)'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ18',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像18 (問題用)'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ19',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像19 (問題用)'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ20',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像20 (問題用)'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ21',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像21 (問題用)'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ22',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像22 (問題用)'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ23',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像23 (問題用)'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ24',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像24 (問題用)'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ25',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像25 (問題用)'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ26',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像26 (問題用)'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ27',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像27 (問題用)'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ28',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像28 (問題用)'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ29',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像29 (問題用)'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='thumbnailQ30',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像30 (問題用)'),
        ),
        migrations.AlterField(
            model_name='codepractice',
            name='thumbnailQ10',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像10 (問題用)'),
        ),
        migrations.AlterField(
            model_name='codepractice',
            name='thumbnailQ6',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像6 (問題用)'),
        ),
        migrations.AlterField(
            model_name='codepractice',
            name='thumbnailQ7',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像7 (問題用)'),
        ),
        migrations.AlterField(
            model_name='codepractice',
            name='thumbnailQ8',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像8 (問題用)'),
        ),
        migrations.AlterField(
            model_name='codepractice',
            name='thumbnailQ9',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像9 (問題用)'),
        ),
    ]
