# Generated by Django 4.2.7 on 2024-01-14 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0008_codepractice_thumbnailq11_codepractice_thumbnailq12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepractice',
            name='answerTitle1',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='ファイル名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codepractice',
            name='answerTitle2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ファイル名'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='answerTitle3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ファイル名'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='answerTitle4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ファイル名'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='answerTitle5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ファイル名'),
        ),
    ]
