# Generated by Django 4.2.7 on 2024-01-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0009_codepractice_answertitle1_codepractice_answertitle2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepractice',
            name='answer6',
            field=models.TextField(blank=True, null=True, verbose_name='正解コード6'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='answer7',
            field=models.TextField(blank=True, null=True, verbose_name='正解コード7'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='answerTitle6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='モジュール名6'),
        ),
        migrations.AddField(
            model_name='codepractice',
            name='answerTitle7',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='モジュール名7'),
        ),
        migrations.AlterField(
            model_name='codepractice',
            name='answer1',
            field=models.TextField(verbose_name='正解コード1'),
        ),
        migrations.AlterField(
            model_name='codepractice',
            name='answer2',
            field=models.TextField(blank=True, null=True, verbose_name='正解コード2'),
        ),
        migrations.AlterField(
            model_name='codepractice',
            name='answer3',
            field=models.TextField(blank=True, null=True, verbose_name='正解コード3'),
        ),
        migrations.AlterField(
            model_name='codepractice',
            name='answer4',
            field=models.TextField(blank=True, null=True, verbose_name='正解コード4'),
        ),
        migrations.AlterField(
            model_name='codepractice',
            name='answer5',
            field=models.TextField(blank=True, null=True, verbose_name='正解コード5'),
        ),
        migrations.AlterField(
            model_name='codepractice',
            name='answerTitle1',
            field=models.CharField(max_length=255, verbose_name='モジュール名1'),
        ),
        migrations.AlterField(
            model_name='codepractice',
            name='answerTitle2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='モジュール名2'),
        ),
        migrations.AlterField(
            model_name='codepractice',
            name='answerTitle3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='モジュール名3'),
        ),
        migrations.AlterField(
            model_name='codepractice',
            name='answerTitle4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='モジュール名4'),
        ),
        migrations.AlterField(
            model_name='codepractice',
            name='answerTitle5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='モジュール名5'),
        ),
    ]
